"""Pydantic validation schemas package."""

from app.schemas.user import (
    UserBase,
    UserCreate,
    UserLogin,
    UserUpdate,
    PasswordChange,
    UserResponse,
)
from app.schemas.token import (
    Token,
    TokenRefreshRequest,
    TokenPayload,
)
from app.schemas.common import (
    MessageResponse,
    ErrorResponse,
)
from app.schemas.file import (
    FileBase,
    FileUploadInit,
    FileUploadInitResponse,
    FileUploadComplete,
    FileVersionInit,
    FileVersionInitResponse,
    FileVersionComplete,
    FileVersionResponse,
    FileUpdate,
    FileMove,
    FileCopy,
    FileDownloadResponse,
    FileResponse,
    FileDetailResponse,
    FileListResponse,
)
from app.schemas.folder import (
    BreadcrumbItem,
    FolderBase,
    FolderCreate,
    FolderUpdate,
    FolderMove,
    FolderResponse,
    FolderDetailResponse,
    FolderTreeItem,
    FolderContentsResponse,
)
from app.schemas.share import (
    ShareCreate,
    ShareUpdate,
    ShareResponse,
    SharedItemResponse,
    SharedWithMeResponse,
    SharedByMeResponse,
)
from app.schemas.link_share import (
    LinkShareCreate,
    LinkShareUpdate,
    LinkShareResponse,
    PublicLinkAccessRequest,
    PublicLinkAccessResponse,
    PublicFolderContentsResponse,
)
from app.schemas.star import (
    StarToggleRequest,
    StarToggleResponse,
    StarResponse,
    StarredListResponse,
)
from app.schemas.activity import (
    ActivityResponse,
    ActivityListResponse,
)
from app.schemas.trash import (
    TrashListResponse,
    TrashRestoreAllResponse,
    TrashEmptyResponse,
)

__all__ = [
    "UserBase",
    "UserCreate",
    "UserLogin",
    "UserUpdate",
    "PasswordChange",
    "UserResponse",
    "Token",
    "TokenRefreshRequest",
    "TokenPayload",
    "MessageResponse",
    "ErrorResponse",
    "FileBase",
    "FileUploadInit",
    "FileUploadInitResponse",
    "FileUploadComplete",
    "FileVersionInit",
    "FileVersionInitResponse",
    "FileVersionComplete",
    "FileVersionResponse",
    "FileUpdate",
    "FileMove",
    "FileCopy",
    "FileDownloadResponse",
    "FileResponse",
    "FileDetailResponse",
    "FileListResponse",
    "BreadcrumbItem",
    "FolderBase",
    "FolderCreate",
    "FolderUpdate",
    "FolderMove",
    "FolderResponse",
    "FolderDetailResponse",
    "FolderTreeItem",
    "FolderContentsResponse",
    "ShareCreate",
    "ShareUpdate",
    "ShareResponse",
    "SharedItemResponse",
    "SharedWithMeResponse",
    "SharedByMeResponse",
    "LinkShareCreate",
    "LinkShareUpdate",
    "LinkShareResponse",
    "PublicLinkAccessRequest",
    "PublicLinkAccessResponse",
    "PublicFolderContentsResponse",
    "StarToggleRequest",
    "StarToggleResponse",
    "StarResponse",
    "StarredListResponse",
    "ActivityResponse",
    "ActivityListResponse",
    "TrashListResponse",
    "TrashRestoreAllResponse",
    "TrashEmptyResponse",
]
